@startuml
title Latihan: Peminjamable dan StatusPinjam
skinparam classAttributeIconSize 0

interface Peminjamable <<interface>> {
  + bolehDipinjam() : boolean
  + masaPinjamHari() : int
}

abstract class Koleksi {
  - kode : String
  - judul : String
  + {abstract} jenis() : String
  + toString() : String
}

class Buku {
  + bolehDipinjam() : boolean
  + masaPinjamHari() : int
}

class Majalah {
  + bolehDipinjam() : boolean
  + masaPinjamHari() : int
}

class Skripsi {
  + bolehDipinjam() : boolean
  + masaPinjamHari() : int
}

enum StatusPinjam <<enumeration>> {
  TERSEDIA
  DIPINJAM
  TERLAMBAT
  HILANG
  + keterangan() : String
}

' Pewarisan: garis penuh
Koleksi <|-- Buku
Koleksi <|-- Majalah
Koleksi <|-- Skripsi

' Realisasi interface: garis putus
Peminjamable <|.. Buku
Peminjamable <|.. Majalah
Peminjamable <|.. Skripsi
@enduml
